# Generated by Django 2.2.24 on 2021-11-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='link',
            field=models.CharField(default='httopppppp', max_length=300),
            preserve_default=False,
        ),
    ]
