# Generated by Django 2.2.24 on 2021-11-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211108_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='troupes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troupe', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
