# Generated by Django 2.2.24 on 2021-11-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211111_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='troupes',
            name='link',
            field=models.TextField(default='willsmith'),
            preserve_default=False,
        ),
    ]
